---
development:
  cloud_name: doz2fuvad
  api_key: '896525676729155'
  api_secret: dxcJg9yFbIHLUEv_h7CHuY7YyHg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: doz2fuvad
  api_key: '896525676729155'
  api_secret: dxcJg9yFbIHLUEv_h7CHuY7YyHg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: doz2fuvad
  api_key: '896525676729155'
  api_secret: dxcJg9yFbIHLUEv_h7CHuY7YyHg
  enhance_image_tag: true
  static_image_support: false
